### ISSUE TITLE
Upload only part of virtual environment to PaaS providers

### ISSUE THREAD

**Issue by littleq0903** [natea/django-deployer#18]
our script will upload the whole virtual environment onto paas provider now, but it is unnecessary, the only folder we used is `<env>/lib/python2.7/site-packages`, so we can do a cleaning action before we upload data onto provider.

not sure it only belongs to App Engine support, maybe other we will use the same mechanism.

@natea could you point out which provider will need this feature (uploading virtual environment onto the platform)?

**Comment by natea** [comment]
Another cleaning action that we need to do (at least for Mezzanine) is to
remove the Django 1.5 folder and the PIL folder from site-packages, since
these are already provided by GAE.

On Sun, Mar 31, 2013 at 11:50 PM, LittleQ (Colin Su) <
notifications@github.com> wrote:

> our script will upload the whole virtual environment onto paas provider
> now, but it is unnecessary, the only folder we used is
> <env>/lib/python2.7/site-packages, so we can do a cleaning action before
> we upload data onto provider.
> 
> not sure it only belongs to App Engine support, maybe other we will use
> the same mechanism.
> 
> @natea https://github.com/natea could you point out which provider will
> need this feature (uploading virtual environment onto the platform)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/natea/django-deployer/issues/18
> .

## 

nate@appsembler.com
+1 (617) 517-4953
http://twitter.com/natea | http://linkedin.com/in/natea

**Comment by littleq0903** [comment]
done
